CREATE TABLE NATION (
    NATIONKEY INT,
    N_NAME STRING,
    N_COMMENT STRING,
    LAST_STATEKEY INT
) FROM FILE '/mnt/ssd/geo_btree/build/15/nation2.dat' LINE DELIMITED CSV (fields := '|');

CREATE TABLE STATES (
    NATIONKEY INT,
    STATEKEY INT,
    S_NAME STRING,
    S_COMMENT STRING,
    LAST_COUNTYKEY INT
) FROM FILE '/mnt/ssd/geo_btree/build/15/states.dat' LINE DELIMITED CSV (fields := '|');

CREATE TABLE COUNTIES (
    NATIONKEY INT,
    STATEKEY INT,
    COUNTYKEY INT,
    C_NAME STRING,
    C_COMMENT STRING,
    LAST_CITYKEY INT
) FROM FILE '/mnt/ssd/geo_btree/build/15/county.dat' LINE DELIMITED CSV (fields := '|');

CREATE TABLE CITIES (
    NATIONKEY INT,
    STATEKEY INT,
    COUNTYKEY INT,
    CITYKEY INT,
    CI_NAME STRING,
    CI_COMMENT STRING
) FROM FILE '/mnt/ssd/geo_btree/build/15/city.dat' LINE DELIMITED CSV (fields := '|');

CREATE STREAM CUSTOMER2 (
    NATIONKEY INT,
    STATEKEY INT,
    COUNTYKEY INT,
    CITYKEY INT,
    CUSTKEY INT,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_PHONE STRING,
    C_ACCTBAL DOUBLE,
    C_MKTSEGMENT STRING,
    C_COMMENT STRING
) FROM FILE '/mnt/ssd/geo_btree/build/15/customer2.dat' LINE DELIMITED CSV (fields := '|');

SELECT *
FROM NATION JOIN STATES
  ON NATION.NATIONKEY = STATES.NATIONKEY
    JOIN COUNTIES
        ON STATES.NATIONKEY = COUNTIES.NATIONKEY
        AND STATES.STATEKEY = COUNTIES.STATEKEY
    JOIN CITIES
        ON COUNTIES.NATIONKEY = CITIES.NATIONKEY
        AND COUNTIES.STATEKEY = CITIES.STATEKEY
        AND COUNTIES.COUNTYKEY = CITIES.COUNTYKEY
    JOIN CUSTOMER2
        ON CITIES.NATIONKEY = CUSTOMER2.NATIONKEY
        AND CITIES.STATEKEY = CUSTOMER2.STATEKEY
        AND CITIES.COUNTYKEY = CUSTOMER2.COUNTYKEY
        AND CITIES.CITYKEY = CUSTOMER2.CITYKEY;