CREATE STREAM NATION (
    NATIONKEY INT,
    N_NAME STRING,
    N_COMMENT STRING,
    LAST_STATEKEY INT
) FROM FILE '/mnt/ssd/geo_btree/build/15/nation2.dat' LINE DELIMITED CSV (fields := ',');

SELECT *
FROM NATION; -- ensure stored

CREATE STREAM STATES (
    NATIONKEY INT,
    STATEKEY INT,
    S_NAME STRING,
    S_COMMENT STRING,
    LAST_COUNTYKEY INT
) FROM FILE '/mnt/ssd/geo_btree/build/15/states.dat' LINE DELIMITED CSV (fields := ',');

SELECT *
FROM STATES; -- ensure stored

CREATE STREAM COUNTY (
    NATIONKEY INT,
    STATEKEY INT,
    COUNTYKEY INT,
    C_NAME STRING,
    C_COMMENT STRING,
    LAST_CITYKEY INT
) FROM FILE '/mnt/ssd/geo_btree/build/15/county.dat' LINE DELIMITED CSV (fields := ',');

SELECT *
FROM COUNTY; -- ensure stored

CREATE STREAM CITY (
    NATIONKEY INT,
    STATEKEY INT,
    COUNTYKEY INT,
    CITYKEY INT,
    CI_NAME STRING,
    CI_COMMENT STRING
) FROM FILE '/mnt/ssd/geo_btree/build/15/city.dat' LINE DELIMITED CSV (fields := ',');

SELECT *
FROM CITY; -- ensure stored

CREATE STREAM CUSTOMER2 (
    NATIONKEY INT,
    STATEKEY INT,
    COUNTYKEY INT,
    CITYKEY INT,
    CUSTKEY INT,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_PHONE STRING,
    C_ACCTBAL DOUBLE,
    C_MKTSEGMENT STRING,
    C_COMMENT STRING
) FROM FILE '/mnt/ssd/geo_btree/build/15/customer2.dat' LINE DELIMITED CSV (fields := ',');

SELECT *
FROM CUSTOMER2; -- ensure stored

SELECT *
FROM NATION JOIN STATES
  ON NATION.NATIONKEY = STATES.NATIONKEY
    JOIN COUNTY
        ON STATES.NATIONKEY = COUNTY.NATIONKEY
        AND STATES.STATEKEY = COUNTY.STATEKEY
    JOIN CITY
        ON COUNTY.NATIONKEY = CITY.NATIONKEY
        AND COUNTY.STATEKEY = CITY.STATEKEY
        AND COUNTY.COUNTYKEY = CITY.COUNTYKEY
    JOIN CUSTOMER2
        ON CITY.NATIONKEY = CUSTOMER2.NATIONKEY
        AND CITY.STATEKEY = CUSTOMER2.STATEKEY
        AND CITY.COUNTYKEY = CUSTOMER2.COUNTYKEY
        AND CITY.CITYKEY = CUSTOMER2.CITYKEY;
-- WHERE NATION.NATIONKEY = ? AND STATES.STATEKEY = ? // Q1
-- WHERE NATION.NATIONKEY = ? AND STATES.STATEKEY = ? AND COUNTY.COUNTYKEY = ? // Q2


SELECT NATION.NATIONKEY, NATION.N_NAME,
         STATES.STATEKEY, STATES.S_NAME,
         COUNTY.COUNTYKEY, COUNTY.C_NAME,
         CITY.CITYKEY, CITY.CI_NAME, COUNT(*)
FROM NATION JOIN STATES
  ON NATION.NATIONKEY = STATES.NATIONKEY
    JOIN COUNTY
        ON STATES.NATIONKEY = COUNTY.NATIONKEY
        AND STATES.STATEKEY = COUNTY.STATEKEY
    JOIN CITY
        ON COUNTY.NATIONKEY = CITY.NATIONKEY
        AND COUNTY.STATEKEY = CITY.STATEKEY
        AND COUNTY.COUNTYKEY = CITY.COUNTYKEY
    JOIN CUSTOMER2
        ON CITY.NATIONKEY = CUSTOMER2.NATIONKEY
        AND CITY.STATEKEY = CUSTOMER2.STATEKEY
        AND CITY.COUNTYKEY = CUSTOMER2.COUNTYKEY
        AND CITY.CITYKEY = CUSTOMER2.CITYKEY
GROUP BY NATION.NATIONKEY, NATION.N_NAME,
         STATES.STATEKEY, STATES.S_NAME,
         COUNTY.COUNTYKEY, COUNTY.C_NAME,
         CITY.CITYKEY, CITY.CI_NAME;
-- WHERE NATION.NATIONKEY = ? AND STATES.STATEKEY = ? // Q3
-- WHERE NATION.NATIONKEY = ? AND STATES.STATEKEY = ? AND COUNTY.COUNTYKEY = ? // Q4

SELECT NATION.NATIONKEY, NATION.N_NAME,
         STATES.STATEKEY, STATES.S_NAME,
         COUNTY.COUNTYKEY, COUNTY.C_NAME,
         CITY.CITYKEY, CITY.CI_NAME, COUNT(DISTINCT CUSTOMER2.C_MKTSEGMENT)
FROM NATION JOIN STATES
  ON NATION.NATIONKEY = STATES.NATIONKEY
    JOIN COUNTY
        ON STATES.NATIONKEY = COUNTY.NATIONKEY
        AND STATES.STATEKEY = COUNTY.STATEKEY
    JOIN CITY
        ON COUNTY.NATIONKEY = CITY.NATIONKEY
        AND COUNTY.STATEKEY = CITY.STATEKEY
        AND COUNTY.COUNTYKEY = CITY.COUNTYKEY
    JOIN CUSTOMER2
        ON CITY.NATIONKEY = CUSTOMER2.NATIONKEY
        AND CITY.STATEKEY = CUSTOMER2.STATEKEY
        AND CITY.COUNTYKEY = CUSTOMER2.COUNTYKEY
        AND CITY.CITYKEY = CUSTOMER2.CITYKEY
GROUP BY NATION.NATIONKEY, NATION.N_NAME,
         STATES.STATEKEY, STATES.S_NAME,
         COUNTY.COUNTYKEY, COUNTY.C_NAME,
         CITY.CITYKEY, CITY.CI_NAME;
-- WHERE NATION.NATIONKEY = ? AND STATES.STATEKEY = ? // Q5
-- WHERE NATION.NATIONKEY = ? AND STATES.STATEKEY = ? AND COUNTY.COUNTYKEY = ? // Q6